flaskr/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__, url_prefix='/Word_of_the_Round')

from . import routes, events

flaskr/home/routes.py
from threading import Lock
from flask import Flask, render_template, session, request, redirect, \
    copy_current_request_context, jsonify, url_for
import json

from .. import socketio
from . import home
from ..models import DataManipulator
import uuid
thread = None
thread_lock = Lock()

data = DataManipulator()

#displays the home page (code in home.html)
@home.route('/home')
def displayHomePage():
    session['joinError'] = False
    return render_template('home.html')

#redirects user to Join a login screen
@home.route('/readHomeButtons', methods=['POST'])
def readHomeButtons():
    urlSuffix = ''
    if request.form.get('joinGameButton') == 'joinGame':
        urlSuffix = '/joineeLoginPage'
    elif request.form.get('createGameButton') == 'createGame':
        urlSuffix = '/hostLoginPage'
    prefix = request.path.rsplit('/', 1)[0]
    return redirect(prefix + urlSuffix)

#displays the lobby page
@home.route('/lobby')
def displayLobby():
    return render_template('lobby.html')

#displays the host login page
@home.route('/hostLoginPage')
def displayLoginPage():
    return render_template('Host Login Page.html')

#displays the joinee login page
@home.route('/joineeLoginPage')
def displayHostLoginPage():
    return render_template('Joinee Login Page.html')

flaskr/templates/End Game.html
<!DOCTYPE html>
<html>

<head>
	<title>Word of the Round: Lobby</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
	<script src="{{url_for('static', filename='js/endGameScript.js')}}"></script>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
</head>
	
<body>
	<h1 id="heading">End of Game</h1>
	<div class="center largeFont" id="playerScores"></div>
	<br>
	<span class="large-br"></span>
	<br>
	<span class="large-br"></span>
	<br>
	<span class="large-br"></span>
	<form id="return" method="POST" action='#'>
		<div class="center">Do you want to return to the lobby?</div>
		<br><br>
		<button class="center button" name="yesbuttonreturntolobby" value="Yes!" type="submit">Yes!</button>
	</form>
	<div class="top-left" id="playerName"></div>
	<form id="leave" method="POST" action='#' class="bottom-left">
		<input type="submit" value="Leave Room">
	</form>
</body>
	
</html>

flaskr/templates/Game Part1.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Word of the Round</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/phase1Script.js')}}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
</head>
<body>
    <h1>Choosing Prompt and Word</h1>
    <span class="medium-br"></span>
    <form id="choosePrompt" method="POST" action='#'>
        <input class="left mark" type="radio" value="Prompt1" name="prompt" id="prompt1Mark" />
        <label class="left button card" for="prompt1Mark" id="Prompt1"></label>
        <input class="center mark" type="radio" value="Prompt1" name="prompt" id="prompt2Mark" />
        <label class="center button card" for="prompt2Mark" id="Prompt2"></label>
        <input class="right mark" type="radio" value="Prompt1" name="prompt" id="prompt3Mark" />
        <label class="right button card" for="prompt3Mark" id="Prompt3"></label>
    </form>
    <br>
    <span class="large-br"></span>
    <br>
    <span class="medium-br"></span>
    <form id="chooseWord" method="POST" action='#'>
        <input class="left mark" type="radio" value="Word1" name="word" id="word1Mark" />
        <label class="left button card" for="word1Mark" id="Word1"></label>
        <input class="center mark" type="radio" value="Word2" name="word" id="word2Mark" />
        <label class="center button card" for="word2Mark" id="Word2"></label>
        <input class="right mark" type="radio" value="Word3" name="word" id="word3Mark" />
        <label class="right button card" for="word3Mark" id="Word3"></label>
    </form>
    <br>
    <span class="medium-br"></span>
    <form id="submitPrompt" method="POST" action='#'>
        <button class="center button" name="nextPhaseButton" value="submittedPrompts" type="submit">Submit</button>
    </form>
    <div class="top-left" id="playerName"></div>
    <div class="top-right" id="win_data"></div>
    <div class="bottom-right" id="playerScores"></div>
    <form id="leave" method="POST" action='#' class="bottom-left">
        <input type="submit" value="Leave Room">
    </form>
</body>
</html>

flaskr/templates/Game Part2.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Word of the Round</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
    <script src="{{url_for('static', filename='js/phase2Script.js')}}"></script>
</head>
<body>
    <h1>Creating Answer</h1>
    <div class="smallFont" id="Prompt"></div>
    <br>
    <div class="smallFont" id="Word"></div>
    <br> <br> <br> <br>
    <form id="enterAnswer" method="POST" action='#'>
        <p align="left">
            <textarea rows="8" cols="80" id="answer">Enter your response here </textarea>
            <br> <br> <br> <br>
            Ready to submit? <button class="button" name="yesButtonplayerResponse" value="Yes!" type="submit">Yes!</button>
            <br> <br> <br> <br>
            <div class="center smallFont" id="error">Your Answer Does not Include the Word</div>
        </p>
    </form>
    <br> <br> <br> <br>
    <div class="center largeFont" id="Waiting">Waiting for Everyone to Submit Their Answers</div>
    <div class="top-left" id="playerName"></div>
    <div class="bottom-right" id="playerScores"></div>
    <div class="top-right" id="win_data"></div>
    <form id="leave" method="POST" action='#' class="bottom-left">
        <input type="submit" value="Leave Room">
    </form>
</body>
</html>

flaskr/templates/Host Login Page.html
<!DOCTYPE html>
<html>

<head>
	<title>Player Login Page</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
	<script src="{{url_for('static', filename='js/hostScript.js')}}"></script>
</head>
	
   <body>
      <form id="hostLobby" method="POST" action='#'>
		  <p align = "center">
         	 Please enter your name: <input type = "text" name = "name" id="name"/>
         	 <br> <br> <br> <br> 
			 Ready to join the lobby? <button class="button" name="yesbuttonlogin" value="Yes!" type="submit">Yes!</button>
			<br><br> <br> <br>
			<img src="{{url_for('static', filename='Logo.png')}}" align="center" />

		  </p>
      </form>
   </body>
	
</html>

flaskr/templates/Joinee Login Page.html
<!DOCTYPE html>
<html>

<head>
	<title>Player Login Page</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
	<script src="{{url_for('static', filename='js/joineeScript.js')}}"></script>
</head>
	
<body>
	<form id="joinLobby" method="POST" action='#'>
		<p align="center">
			Please enter your name: <input type="text" name="name" id="name"/>
			<br> <br> <br> <br>
			Game ID: <input type="text" name="game id" id="game id" />
			<br><br> <br> <br>
			Ready to join the lobby? <button class="button" name="yesbuttonlogin" value="Yes!" type="submit">Yes!</button>
			<br><br> <br> <br>
			<img src="{{url_for('static', filename='Logo.png')}}" align="center" />
		</p>
	</form>
	<p id="error" align ="center"></p>
</body>
	
</html>

flaskr/templates/JudgeChoosingCard.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Word of the Round</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
	<script src="{{url_for('static', filename='js/phase3Script.js')}}"></script>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
</head>
	
<body>
	<h1>Choosing Answer</h1>
	<span class="small-br"></span>
	<p align="left">
		<div class="smallFont" id="Prompt"></div>
		<br>
		<div class="smallFont" id="Word"></div>
		<br><br>
		Now, please select the best player response:
	</p>
	<form id="chooseWord" method="POST" action='#'>
		<input class="left mark" type="radio" value="answerNumber1" name="answer" id="answerMark1" />
		<label class="left button card smallFont" for="answerMark1" id="answerNumber1"></label>
		<input class="center mark" type="radio" value="answerNumber2" name="answer" id="answerMark2" />
		<label class="center button card smallFont" for="answerMark2" id="answerNumber2"></label>
		<input class="right mark" type="radio" value="answerNumber3" name="answer" id="answerMark3" />
		<label class="right button card smallFont" for="answerMark3" id="answerNumber3"></label>
		<br>
		<span class="large-br"></span>
		<input class="left mark" type="radio" value="answerNumber4" name="answer" id="answerMark4" />
		<label class="left button card smallFont" for="answerMark4" id="answerNumber4"></label>
		<input class="center mark" type="radio" value="answerNumber5" name="answer" id="answerMark5" />
		<label class="center button card smallFont" for="answerMark5" id="answerNumber5"></label>
		<input class="right mark" type="radio" value="answerNumber6" name="answer" id="answerMark6" />
		<label class="right button card smallFont" for="answerMark6" id="answerNumber6"></label>
	</form>
	<br>
	<span class="medium-br"></span>
	<br>
	<span class="medium-br"></span>
	<form id="chooseAnswer" method="POST" action='#'>
		<button class="center button" name="nextPhaseButton" value="submittedPrompts" type="submit">Submit</button>
	</form>
	<div class="top-left" id="playerName"></div>
	<div class="bottom-right" id="playerScores"></div>
	<div class="top-right" id="win_data"></div>
	<form id="leave" method="POST" action='#' class="bottom-left">
		<input type="submit" value="Leave Room">
	</form>
</body>
	
</html>

flaskr/templates/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Word of the Round</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
</head>

<body>
    <h1><img src="{{url_for('static', filename='Logo.png')}}" align="center" /></h1>
	
<center>
	<br> 
<p> Word of the Round is an exciting game that encourages creativity and competition among family and friend groups.
	<br> <br>	
  Each round, players will have multiple lines to respond to the judge’s chosen prompt. 
	<br> <br>
The only catch… they must incorporate the judge’s chosen word, the Word of the Round, into their response. 
<br> <br>
Have fun, and see where your imagination takes you!


</center>
    <span class="large-br"></span>
    <form action="{{ url_for('home.readHomeButtons') }}" method="post">
        <button class="center button" name="joinGameButton" value="joinGame">Join Game</button>
        <br />
        <span class="large-br"></span>
        <button class="center button" name="createGameButton" value="createGame">Create Game</button>
    </form>
</p>
</body>
</html>

flaskr/templates/lobby.html
<!DOCTYPE HTML>
<html>
<head>
    <title>Word of the Round: Lobby</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.4/socket.io.js" integrity="sha512-aMGMvNYu8Ue4G+fHa359jcPb1u+ytAF+P2SCb+PxrjCdO3n3ZTxJ30zuH39rimUggmTwmh2u7wvQsDTHESnmfQ==" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/lobbyScript.js')}}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homeStyle.css') }}">
</head>
<body>
    <h1>Lobby Page</h1>
    <p id="game_code"></p>
    <p id="player_list"></p>
    <form id="leave" method="POST" action='#'>
        <input type="submit" value="Leave Room">
    </form>
    <form id="start" method="POST" action='#'>
        <button class="center button" name="startGameButton" value="Start Game" type="submit">Start</button>
        <br>
        <span class="medium-br"></span>
        <p align="center">
            Time Limit:
            <input type="radio" name="Time Limit" id="Time Limit" value="30"> 30s
            <input type="radio" name="Time Limit" id="Time Limit" value="60"> 60s
            <input type="radio" name="Time Limit" id="Time Limit" value="90" checked> 90s
            <input type="radio" name="Time Limit" id="Time Limit" value="120"> 120s
            <br>

            Word Difficulty:
            <input type="radio" name="Word Difficulty" id="Word Difficulty" value="easy"> Easy
            <input type="radio" name="Word Difficulty" id="Word Difficulty" value="medium" checked> Medium
            <input type="radio" name="Word Difficulty" id="Word Difficulty" value="hard"> Hard
            <br>

            Word Count Limit for Responses:
            <input type="radio" name="Word Count Limit" id="Word Count Limit" value="50"> 50
            <input type="radio" name="Word Count Limit" id="Word Count Limit" value="100" checked> 100
            <input type="radio" name="Word Count Limit" id="Word Count Limit" value="200"> 200
            <br>

            First to How Many to Win: <span id="win_output"></span>
            <div class="center slidecontainer">
                <input type="range" min="1" max="10" value="5" class="slider" id="win_data">
            </div>
            <br>
        </p>
    </form>
    <h2>Send:</h2>
    <form id="send_room" method="POST" action='#'>
        <input type="text" name="room_data" id="room_data" placeholder="Message">
        <input type="submit" value="Send to Room">
    </form>
    <br />
    <div id="error" class="center"></div>
    <br />
    <h2>Receive:</h2>
    <div id="log"></div>
</body>
</html>